version: "3.7"
networks: 
  laradocker:
    driver: bridge
services:
  app:
    build: 
      args: 
        user: rajat
        uid: 1001
      context: ./.docker
      dockerfile: Dockerfile
    image: laradocker
    container_name: laradocker-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
      - ./.docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - laradocker

  db:
    image: mysql:5.7
    container_name: laradocker-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'lara_db'
      MYSQL_ROOT_PASSWORD: 'Yz0Kp6wZnl8YWXRe'
      MYSQL_PASSWORD: 'Yz0Kp6wZnl8YWXRe'
      MYSQL_USER: 'rajat'
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laradocker

  nginx:
    image: nginx:1.17-alpine
    container_name: laradocker-nginx
    restart: unless-stopped
    ports:
      - 8008:80
    volumes:
      - ./src:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d
    networks:
      - laradocker
